
// APP Manager Constants
const APP_STATE_HEADER_CLASS_REMOVE = 'HEADER_REMOVE_CLASSNAME';
const APP_STATE_HEADER_CLASS_ADD = 'HEADER_ADD_CLASSNAME';
const APP_STATE_PAGEVIEW = 'APP_STATE_PAGE_CHANGED';

export {
  APP_STATE_HEADER_CLASS_REMOVE,
  APP_STATE_HEADER_CLASS_ADD,
  APP_STATE_PAGEVIEW,
};
